version: '3'

services:
  server:
    build: .
    volumes: 
      - ./:/app
    ports: 
      - 8080:3001
    env_file:
      - .env
    links: 
      - database
    command: ['npm', 'start']
  database:
    image: postgres:9.6-alpine
    environment: 
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: case_mercado_libre
    ports:
      - 11543:5432
    volumes: 
      - database-data:/var/lib/postgresql/data
volumes: 
  database-data: {}